### ISSUE TITLE
retry request vote rpc?

### ISSUE THREAD

**Issue by marcusgao94** [shishujuan/mit6.824-2017-raft#1]
the paper says 

> Servers retry RPCs if they do not receive a re- sponse in a timely manner, and they issue RPCs in parallel for best performance.

however in your implementation in LeaderElection 
```
ret := rf.sendRequestVote(idx, args, reply)
if ret {
  rf.mu.Lock()
  defer rf.mu.Unlock()
  if reply.Term > rf.currentTerm {
    rf.convertToFollower(reply.Term)
    return
  }

  if !rf.checkState(Candidate, args.Term) {
    return
  }

  if reply.VoteGranted {
    atomic.AddInt32(&numVoted, 1)
  }

  if atomic.LoadInt32(&numVoted) > int32(len(rf.peers)/2) {
    DPrintf("Server(%d) win vote", rf.me)
    // 这两句调用顺序很重要
    rf.convertToLeader()
    dropAndSet(rf.leaderCh)
  }
}
```
you only call sendRequestVote once and check reply is ok. If reply is not ok shouldn't you retry calling sendRequestVote?

**Comment by shishujuan** [comment]
@marcusgao94  
func Make(peers []*labrpc.ClientEnd, me int,...)
中有个主循环，如果选举不成功会随机等待一段时间后重新发起选举。
